language: go

os:
  - linux
  - osx
  - windows
go:
- 1.13.x

before_install:
  - go get ./...
  - go get github.com/wailsapp/wails/cmd/wails
install:
  - chmod +x install.sh && ./install.sh
script:
  - wails build
  - ls
