# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\FriendlyUser\WailsTest
environment:
  GOPATH: c:\gopath

stack: go 1.13

before_test:
  - choco install -y nodejs
  - choco install -y mingw
  - refreshenv
  - go get ./...
  - node --version || true || npm --version
  - set GOMODULES=on || true
  - go get ./...
  - go get -u github.com/wailsapp/wails/cmd/wails
  - refreshenv
  - c:\gopath\src\github.com\wailsapp\wails version || true

test_script:
  - c:\gopath\src\github.com\wailsapp\wails build