version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: choco install -y qt-sdk-windows-x64-mingw_sjlj
      - run: go get ./...
      - run: go get -u github.com/wailsapp/wails/cmd/wails
      - run: wails build