version: 2.1

orbs:
  win: circleci/windows@2.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: choco install -y mingw
      - run: go get github.com/leaanthony/mewn/cmd/mewn
      - run: go get ./...
      - run: go get -u github.com/wailsapp/wails/cmd/wails
      - run: go env GOPATH
      - run: cmd  /c "mklink mewn C:/Users/circleci/go/bin/mewn" || true
      - run: cmd  /c "mklink wails C:/Users/circleci/go/bin/wails" || true
      - run: source ~/.bashrc || true
      - run: ./resetEnv.bat || true
      - run: C:/Users/circleci/go/bin/wails build || true
      - run: C:/Users/circleci/go/bin/wails build || true
      - run: wails build || true
      - run: wails build || true
