version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout
      - run: choco install -y strawberryperl || true
      - run: go get ./...
      - run: go get -u github.com/wailsapp/wails/cmd/wails
      - run: ./resetEnv.bat || true
      - run: go env GOPATH
      - run: $GOPATH/wails build || true
      - run: $GOPATH/wails build || true